#!/usr/bin/env bash
set -x
set -e

source /common.sh

if [ "$OCTOPI_INCLUDE_NETCONNECTD" == "yes" ]
then
  apt-get remove -y --purge raspberrypi-net-mods dhcpcd5 || true
  unpack /filesystem/root-pre /
fi
